use crate::content::operation::Operand;

pub static STANDARD_ENCODING: [Option<&'static str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("exclam"),
    Some("quotedbl"),
    Some("numbersign"),
    Some("dollar"),
    Some("percent"),
    Some("ampersand"),
    Some("quoteright"),
    Some("parenleft"),
    Some("parenright"),
    Some("asterisk"),
    Some("plus"),
    Some("comma"),
    Some("hyphen"),
    Some("period"),
    Some("slash"),
    Some("zero"),
    Some("one"),
    Some("two"),
    Some("three"),
    Some("four"),
    Some("five"),
    Some("six"),
    Some("seven"),
    Some("eight"),
    Some("nine"),
    Some("colon"),
    Some("semicolon"),
    Some("less"),
    Some("equal"),
    Some("greater"),
    Some("question"),
    Some("at"),
    Some("A"),
    Some("B"),
    Some("C"),
    Some("D"),
    Some("E"),
    Some("F"),
    Some("G"),
    Some("H"),
    Some("I"),
    Some("J"),
    Some("K"),
    Some("L"),
    Some("M"),
    Some("N"),
    Some("O"),
    Some("P"),
    Some("Q"),
    Some("R"),
    Some("S"),
    Some("T"),
    Some("U"),
    Some("V"),
    Some("W"),
    Some("X"),
    Some("Y"),
    Some("Z"),
    Some("bracketleft"),
    Some("backslash"),
    Some("bracketright"),
    Some("asciicircum"),
    Some("underscore"),
    Some("quoteleft"),
    Some("a"),
    Some("b"),
    Some("c"),
    Some("d"),
    Some("e"),
    Some("f"),
    Some("g"),
    Some("h"),
    Some("i"),
    Some("j"),
    Some("k"),
    Some("l"),
    Some("m"),
    Some("n"),
    Some("o"),
    Some("p"),
    Some("q"),
    Some("r"),
    Some("s"),
    Some("t"),
    Some("u"),
    Some("v"),
    Some("w"),
    Some("x"),
    Some("y"),
    Some("z"),
    Some("braceleft"),
    Some("bar"),
    Some("braceright"),
    Some("asciitilde"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("exclamdown"),
    Some("cent"),
    Some("sterling"),
    Some("fraction"),
    Some("yen"),
    Some("florin"),
    Some("section"),
    Some("currency"),
    Some("quotesingle"),
    Some("quotedblleft"),
    Some("guillemotleft"),
    Some("guilsinglleft"),
    Some("guilsinglright"),
    Some("fi"),
    Some("fl"),
    None,
    Some("endash"),
    Some("dagger"),
    Some("daggerdbl"),
    Some("periodcentered"),
    None,
    Some("paragraph"),
    Some("bullet"),
    Some("quotesinglbase"),
    Some("quotedblbase"),
    Some("quotedblright"),
    Some("guillemotright"),
    Some("ellipsis"),
    Some("perthousand"),
    None,
    Some("questiondown"),
    None,
    Some("grave"),
    Some("acute"),
    Some("circumflex"),
    Some("tilde"),
    Some("macron"),
    Some("breve"),
    Some("dotaccent"),
    Some("dieresis"),
    None,
    Some("ring"),
    Some("cedilla"),
    None,
    Some("hungarumlaut"),
    Some("ogonek"),
    Some("caron"),
    Some("emdash"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("AE"),
    None,
    Some("ordfeminine"),
    None,
    None,
    Some("Lslash"),
    None,
    Some("Oslash"),
    Some("OE"),
    Some("ordmasculine"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some("ae"),
    None,
    None,
    None,
    Some("dotlessi"),
    None,
    None,
    Some("lslash"),
    None,
    Some("oslash"),
    Some("oe"),
    Some("germandbls"),
    None,
    None,
    None,
];

pub static WIN_ANSI_ENCODING: [Option<&'static str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("exclam"),
    Some("quotedbl"),
    Some("numbersign"),
    Some("dollar"),
    Some("percent"),
    Some("ampersand"),
    Some("quotesingle"),
    Some("parenleft"),
    Some("parenright"),
    Some("asterisk"),
    Some("plus"),
    Some("comma"),
    Some("hyphen"),
    Some("period"),
    Some("slash"),
    Some("zero"),
    Some("one"),
    Some("two"),
    Some("three"),
    Some("four"),
    Some("five"),
    Some("six"),
    Some("seven"),
    Some("eight"),
    Some("nine"),
    Some("colon"),
    Some("semicolon"),
    Some("less"),
    Some("equal"),
    Some("greater"),
    Some("question"),
    Some("at"),
    Some("A"),
    Some("B"),
    Some("C"),
    Some("D"),
    Some("E"),
    Some("F"),
    Some("G"),
    Some("H"),
    Some("I"),
    Some("J"),
    Some("K"),
    Some("L"),
    Some("M"),
    Some("N"),
    Some("O"),
    Some("P"),
    Some("Q"),
    Some("R"),
    Some("S"),
    Some("T"),
    Some("U"),
    Some("V"),
    Some("W"),
    Some("X"),
    Some("Y"),
    Some("Z"),
    Some("bracketleft"),
    Some("backslash"),
    Some("bracketright"),
    Some("asciicircum"),
    Some("underscore"),
    Some("grave"),
    Some("a"),
    Some("b"),
    Some("c"),
    Some("d"),
    Some("e"),
    Some("f"),
    Some("g"),
    Some("h"),
    Some("i"),
    Some("j"),
    Some("k"),
    Some("l"),
    Some("m"),
    Some("n"),
    Some("o"),
    Some("p"),
    Some("q"),
    Some("r"),
    Some("s"),
    Some("t"),
    Some("u"),
    Some("v"),
    Some("w"),
    Some("x"),
    Some("y"),
    Some("z"),
    Some("braceleft"),
    Some("bar"),
    Some("braceright"),
    Some("asciitilde"),
    None,
    Some("Euro"),
    None,
    Some("quotesinglbase"),
    Some("florin"),
    Some("quotedblbase"),
    Some("ellipsis"),
    Some("dagger"),
    Some("daggerdbl"),
    Some("circumflex"),
    Some("perthousand"),
    Some("Scaron"),
    Some("guilsinglleft"),
    Some("OE"),
    None,
    Some("Zcaron"),
    None,
    None,
    Some("quoteleft"),
    Some("quoteright"),
    Some("quotedblleft"),
    Some("quotedblright"),
    Some("bullet"),
    Some("endash"),
    Some("emdash"),
    Some("tilde"),
    Some("trademark"),
    Some("scaron"),
    Some("guilsinglright"),
    Some("oe"),
    None,
    Some("zcaron"),
    Some("Ydieresis"),
    Some("space"),
    Some("exclamdown"),
    Some("cent"),
    Some("sterling"),
    Some("currency"),
    Some("yen"),
    Some("bar"),
    Some("section"),
    Some("dieresis"),
    Some("copyright"),
    Some("ordfeminine"),
    Some("guillemotleft"),
    Some("logicalnot"),
    Some("hyphen"),
    Some("registered"),
    Some("macron"),
    Some("degree"),
    Some("plusminus"),
    Some("twosuperior"),
    Some("threesuperior"),
    Some("acute"),
    Some("mu"),
    Some("paragraph"),
    Some("periodcentered"),
    Some("cedilla"),
    Some("onesuperior"),
    Some("ordmasculine"),
    Some("guillemotright"),
    Some("onequarter"),
    Some("onehalf"),
    Some("threequarters"),
    Some("questiondown"),
    Some("Agrave"),
    Some("Aacute"),
    Some("Acircumflex"),
    Some("Atilde"),
    Some("Adieresis"),
    Some("Aring"),
    Some("AE"),
    Some("Ccedilla"),
    Some("Egrave"),
    Some("Eacute"),
    Some("Ecircumflex"),
    Some("Edieresis"),
    Some("Igrave"),
    Some("Iacute"),
    Some("Icircumflex"),
    Some("Idieresis"),
    Some("Eth"),
    Some("Ntilde"),
    Some("Ograve"),
    Some("Oacute"),
    Some("Ocircumflex"),
    Some("Otilde"),
    Some("Odieresis"),
    Some("multiply"),
    Some("Oslash"),
    Some("Ugrave"),
    Some("Uacute"),
    Some("Ucircumflex"),
    Some("Udieresis"),
    Some("Yacute"),
    Some("Thorn"),
    Some("germandbls"),
    Some("agrave"),
    Some("aacute"),
    Some("acircumflex"),
    Some("atilde"),
    Some("adieresis"),
    Some("aring"),
    Some("ae"),
    Some("ccedilla"),
    Some("egrave"),
    Some("eacute"),
    Some("ecircumflex"),
    Some("edieresis"),
    Some("igrave"),
    Some("iacute"),
    Some("icircumflex"),
    Some("idieresis"),
    Some("eth"),
    Some("ntilde"),
    Some("ograve"),
    Some("oacute"),
    Some("ocircumflex"),
    Some("otilde"),
    Some("odieresis"),
    Some("divide"),
    Some("oslash"),
    Some("ugrave"),
    Some("uacute"),
    Some("ucircumflex"),
    Some("udieresis"),
    Some("yacute"),
    Some("thorn"),
    Some("ydieresis"),
];

pub static MAC_ROMAN_ENCODING: [Option<&'static str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("exclam"),
    Some("quotedbl"),
    Some("numbersign"),
    Some("dollar"),
    Some("percent"),
    Some("ampersand"),
    Some("quotesingle"),
    Some("parenleft"),
    Some("parenright"),
    Some("asterisk"),
    Some("plus"),
    Some("comma"),
    Some("hyphen"),
    Some("period"),
    Some("slash"),
    Some("zero"),
    Some("one"),
    Some("two"),
    Some("three"),
    Some("four"),
    Some("five"),
    Some("six"),
    Some("seven"),
    Some("eight"),
    Some("nine"),
    Some("colon"),
    Some("semicolon"),
    Some("less"),
    Some("equal"),
    Some("greater"),
    Some("question"),
    Some("at"),
    Some("A"),
    Some("B"),
    Some("C"),
    Some("D"),
    Some("E"),
    Some("F"),
    Some("G"),
    Some("H"),
    Some("I"),
    Some("J"),
    Some("K"),
    Some("L"),
    Some("M"),
    Some("N"),
    Some("O"),
    Some("P"),
    Some("Q"),
    Some("R"),
    Some("S"),
    Some("T"),
    Some("U"),
    Some("V"),
    Some("W"),
    Some("X"),
    Some("Y"),
    Some("Z"),
    Some("bracketleft"),
    Some("backslash"),
    Some("bracketright"),
    Some("asciicircum"),
    Some("underscore"),
    Some("grave"),
    Some("a"),
    Some("b"),
    Some("c"),
    Some("d"),
    Some("e"),
    Some("f"),
    Some("g"),
    Some("h"),
    Some("i"),
    Some("j"),
    Some("k"),
    Some("l"),
    Some("m"),
    Some("n"),
    Some("o"),
    Some("p"),
    Some("q"),
    Some("r"),
    Some("s"),
    Some("t"),
    Some("u"),
    Some("v"),
    Some("w"),
    Some("x"),
    Some("y"),
    Some("z"),
    Some("braceleft"),
    Some("bar"),
    Some("braceright"),
    Some("asciitilde"),
    None,
    Some("Adieresis"),
    Some("Aring"),
    Some("Ccedilla"),
    Some("Eacute"),
    Some("Ntilde"),
    Some("Odieresis"),
    Some("Udieresis"),
    Some("aacute"),
    Some("agrave"),
    Some("acircumflex"),
    Some("adieresis"),
    Some("atilde"),
    Some("aring"),
    Some("ccedilla"),
    Some("eacute"),
    Some("egrave"),
    Some("ecircumflex"),
    Some("edieresis"),
    Some("iacute"),
    Some("igrave"),
    Some("icircumflex"),
    Some("idieresis"),
    Some("ntilde"),
    Some("oacute"),
    Some("ograve"),
    Some("ocircumflex"),
    Some("odieresis"),
    Some("otilde"),
    Some("uacute"),
    Some("ugrave"),
    Some("ucircumflex"),
    Some("udieresis"),
    Some("dagger"),
    Some("degree"),
    Some("cent"),
    Some("sterling"),
    Some("section"),
    Some("bullet"),
    Some("paragraph"),
    Some("germandbls"),
    Some("registered"),
    Some("copyright"),
    Some("trademark"),
    Some("acute"),
    Some("dieresis"),
    None,
    Some("AE"),
    Some("Oslash"),
    None,
    Some("plusminus"),
    None,
    None,
    Some("yen"),
    Some("mu"),
    None,
    None,
    None,
    None,
    None,
    Some("ordfeminine"),
    Some("ordmasculine"),
    None,
    Some("ae"),
    Some("oslash"),
    Some("questiondown"),
    Some("exclamdown"),
    Some("logicalnot"),
    None,
    Some("florin"),
    None,
    None,
    Some("guillemotleft"),
    Some("guillemotright"),
    Some("ellipsis"),
    Some("space"),
    Some("Agrave"),
    Some("Atilde"),
    Some("Otilde"),
    Some("OE"),
    Some("oe"),
    Some("endash"),
    Some("emdash"),
    Some("quotedblleft"),
    Some("quotedblright"),
    Some("quoteleft"),
    Some("quoteright"),
    Some("divide"),
    None,
    Some("ydieresis"),
    Some("Ydieresis"),
    Some("fraction"),
    Some("currency"),
    Some("guilsinglleft"),
    Some("guilsinglright"),
    Some("fi"),
    Some("fl"),
    Some("daggerdbl"),
    Some("periodcentered"),
    Some("quotesinglbase"),
    Some("quotedblbase"),
    Some("perthousand"),
    Some("Acircumflex"),
    Some("Ecircumflex"),
    Some("Aacute"),
    Some("Edieresis"),
    Some("Egrave"),
    Some("Iacute"),
    Some("Icircumflex"),
    Some("Idieresis"),
    Some("Igrave"),
    Some("Oacute"),
    Some("Ocircumflex"),
    None,
    Some("Ograve"),
    Some("Uacute"),
    Some("Ucircumflex"),
    Some("Ugrave"),
    Some("dotlessi"),
    Some("circumflex"),
    Some("tilde"),
    Some("macron"),
    Some("breve"),
    Some("dotaccent"),
    Some("ring"),
    Some("cedilla"),
    Some("hungarumlaut"),
    Some("ogonek"),
    Some("caron"),
];

pub static PDF_DOC_ENCODING: [Option<&'static str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("fi"),
    Some("fl"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("exclam"),
    Some("quotedbl"),
    Some("numbersign"),
    Some("dollar"),
    Some("percent"),
    Some("ampersand"),
    Some("quotesingle"),
    Some("parenleft"),
    Some("parenright"),
    Some("asterisk"),
    Some("plus"),
    Some("comma"),
    Some("hyphen"),
    Some("period"),
    Some("slash"),
    Some("zero"),
    Some("one"),
    Some("two"),
    Some("three"),
    Some("four"),
    Some("five"),
    Some("six"),
    Some("seven"),
    Some("eight"),
    Some("nine"),
    Some("colon"),
    Some("semicolon"),
    Some("less"),
    Some("equal"),
    Some("greater"),
    Some("question"),
    Some("at"),
    Some("A"),
    Some("B"),
    Some("C"),
    Some("D"),
    Some("E"),
    Some("F"),
    Some("G"),
    Some("H"),
    Some("I"),
    Some("J"),
    Some("K"),
    Some("L"),
    Some("M"),
    Some("N"),
    Some("O"),
    Some("P"),
    Some("Q"),
    Some("R"),
    Some("S"),
    Some("T"),
    Some("U"),
    Some("V"),
    Some("W"),
    Some("X"),
    Some("Y"),
    Some("Z"),
    Some("bracketleft"),
    Some("backslash"),
    Some("bracketright"),
    Some("asciicircum"),
    Some("underscore"),
    Some("grave"),
    Some("a"),
    Some("b"),
    Some("c"),
    Some("d"),
    Some("e"),
    Some("f"),
    Some("g"),
    Some("h"),
    Some("i"),
    Some("j"),
    Some("k"),
    Some("l"),
    Some("m"),
    Some("n"),
    Some("o"),
    Some("p"),
    Some("q"),
    Some("r"),
    Some("s"),
    Some("t"),
    Some("u"),
    Some("v"),
    Some("w"),
    Some("x"),
    Some("y"),
    Some("z"),
    Some("braceleft"),
    Some("bar"),
    Some("braceright"),
    Some("asciitilde"),
    None,
    Some("Euro"),
    None,
    Some("quotesinglbase"),
    Some("florin"),
    Some("quotedblbase"),
    Some("ellipsis"),
    Some("dagger"),
    Some("daggerdbl"),
    Some("circumflex"),
    Some("perthousand"),
    Some("Scaron"),
    Some("guilsinglleft"),
    Some("OE"),
    None,
    Some("Zcaron"),
    None,
    None,
    Some("quoteleft"),
    Some("quoteright"),
    Some("quotedblleft"),
    Some("quotedblright"),
    Some("bullet"),
    Some("endash"),
    Some("emdash"),
    Some("tilde"),
    Some("trademark"),
    Some("scaron"),
    Some("guilsinglright"),
    Some("oe"),
    None,
    Some("zcaron"),
    Some("Ydieresis"),
    Some("space"),
    Some("exclamdown"),
    Some("cent"),
    Some("sterling"),
    Some("currency"),
    Some("yen"),
    Some("bar"),
    Some("section"),
    Some("dieresis"),
    Some("copyright"),
    Some("ordfeminine"),
    Some("guillemotleft"),
    Some("logicalnot"),
    Some("hyphen"),
    Some("registered"),
    Some("macron"),
    Some("degree"),
    Some("plusminus"),
    Some("twosuperior"),
    Some("threesuperior"),
    Some("acute"),
    Some("mu"),
    Some("paragraph"),
    Some("periodcentered"),
    Some("cedilla"),
    Some("onesuperior"),
    Some("ordmasculine"),
    Some("guillemotright"),
    Some("onequarter"),
    Some("onehalf"),
    Some("threequarters"),
    Some("questiondown"),
    Some("Agrave"),
    Some("Aacute"),
    Some("Acircumflex"),
    Some("Atilde"),
    Some("Adieresis"),
    Some("Aring"),
    Some("AE"),
    Some("Ccedilla"),
    Some("Egrave"),
    Some("Eacute"),
    Some("Ecircumflex"),
    Some("Edieresis"),
    Some("Igrave"),
    Some("Iacute"),
    Some("Icircumflex"),
    Some("Idieresis"),
    Some("Eth"),
    Some("Ntilde"),
    Some("Ograve"),
    Some("Oacute"),
    Some("Ocircumflex"),
    Some("Otilde"),
    Some("Odieresis"),
    Some("multiply"),
    Some("Oslash"),
    Some("Ugrave"),
    Some("Uacute"),
    Some("Ucircumflex"),
    Some("Udieresis"),
    Some("Yacute"),
    Some("Thorn"),
    Some("germandbls"),
    Some("agrave"),
    Some("aacute"),
    Some("acircumflex"),
    Some("atilde"),
    Some("adieresis"),
    Some("aring"),
    Some("ae"),
    Some("ccedilla"),
    Some("egrave"),
    Some("eacute"),
    Some("ecircumflex"),
    Some("edieresis"),
    Some("igrave"),
    Some("iacute"),
    Some("icircumflex"),
    Some("idieresis"),
    Some("eth"),
    Some("ntilde"),
    Some("ograve"),
    Some("oacute"),
    Some("ocircumflex"),
    Some("otilde"),
    Some("odieresis"),
    Some("divide"),
    Some("oslash"),
    Some("ugrave"),
    Some("uacute"),
    Some("ucircumflex"),
    Some("udieresis"),
    Some("yacute"),
    Some("thorn"),
    Some("ydieresis"),
];

// ---------------------------------------------------------------------------
// Symbol and ZapfDingbats built-in encodings (PDF spec Appendix D.4/D.5).
// These standard-14 fonts carry their own encodings (not StandardEncoding);
// codes map to Symbol/ZapfDingbats glyph names. Used for symbolic-font
// fallback rendering.
// ---------------------------------------------------------------------------

static SYMBOL_ENCODING: [Option<&str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("exclam"),
    Some("universal"),
    Some("numbersign"),
    Some("existential"),
    Some("percent"),
    Some("ampersand"),
    Some("suchthat"),
    Some("parenleft"),
    Some("parenright"),
    Some("asteriskmath"),
    Some("plus"),
    Some("comma"),
    Some("minus"),
    Some("period"),
    Some("slash"),
    Some("zero"),
    Some("one"),
    Some("two"),
    Some("three"),
    Some("four"),
    Some("five"),
    Some("six"),
    Some("seven"),
    Some("eight"),
    Some("nine"),
    Some("colon"),
    Some("semicolon"),
    Some("less"),
    Some("equal"),
    Some("greater"),
    Some("question"),
    Some("congruent"),
    Some("Alpha"),
    Some("Beta"),
    Some("Chi"),
    Some("Delta"),
    Some("Epsilon"),
    Some("Phi"),
    Some("Gamma"),
    Some("Eta"),
    Some("Iota"),
    Some("theta1"),
    Some("Kappa"),
    Some("Lambda"),
    Some("Mu"),
    Some("Nu"),
    Some("Omicron"),
    Some("Pi"),
    Some("Theta"),
    Some("Rho"),
    Some("Sigma"),
    Some("Tau"),
    Some("Upsilon"),
    Some("sigma1"),
    Some("Omega"),
    Some("Xi"),
    Some("Psi"),
    Some("Zeta"),
    Some("bracketleft"),
    Some("therefore"),
    Some("bracketright"),
    Some("perpendicular"),
    Some("underscore"),
    Some("radicalex"),
    Some("alpha"),
    Some("beta"),
    Some("chi"),
    Some("delta"),
    Some("epsilon"),
    Some("phi"),
    Some("gamma"),
    Some("eta"),
    Some("iota"),
    Some("phi1"),
    Some("kappa"),
    Some("lambda"),
    Some("mu"),
    Some("nu"),
    Some("omicron"),
    Some("pi"),
    Some("theta"),
    Some("rho"),
    Some("sigma"),
    Some("tau"),
    Some("upsilon"),
    Some("omega1"),
    Some("omega"),
    Some("xi"),
    Some("psi"),
    Some("zeta"),
    Some("braceleft"),
    Some("bar"),
    Some("braceright"),
    Some("similar"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("Euro"),
    Some("Upsilon1"),
    Some("minute"),
    Some("lessequal"),
    Some("fraction"),
    Some("infinity"),
    Some("florin"),
    Some("club"),
    Some("diamond"),
    Some("heart"),
    Some("spade"),
    Some("arrowboth"),
    Some("arrowleft"),
    Some("arrowup"),
    Some("arrowright"),
    Some("arrowdown"),
    Some("degree"),
    Some("plusminus"),
    Some("second"),
    Some("greaterequal"),
    Some("multiply"),
    Some("proportional"),
    Some("partialdiff"),
    Some("bullet"),
    Some("divide"),
    Some("notequal"),
    Some("equivalence"),
    Some("approxequal"),
    Some("ellipsis"),
    Some("arrowvertex"),
    Some("arrowhorizex"),
    Some("carriagereturn"),
    Some("aleph"),
    Some("Ifraktur"),
    Some("Rfraktur"),
    Some("weierstrass"),
    Some("circlemultiply"),
    Some("circleplus"),
    Some("emptyset"),
    Some("intersection"),
    Some("union"),
    Some("propersuperset"),
    Some("reflexsuperset"),
    Some("notsubset"),
    Some("propersubset"),
    Some("reflexsubset"),
    Some("element"),
    Some("notelement"),
    Some("angle"),
    Some("gradient"),
    Some("registerserif"),
    Some("copyrightserif"),
    Some("trademarkserif"),
    Some("product"),
    Some("radical"),
    Some("dotmath"),
    Some("logicalnot"),
    Some("logicaland"),
    Some("logicalor"),
    Some("arrowdblboth"),
    Some("arrowdblleft"),
    Some("arrowdblup"),
    Some("arrowdblright"),
    Some("arrowdbldown"),
    Some("lozenge"),
    Some("angleleft"),
    Some("registersans"),
    Some("copyrightsans"),
    Some("trademarksans"),
    Some("summation"),
    Some("parenlefttp"),
    Some("parenleftex"),
    Some("parenleftbt"),
    Some("bracketlefttp"),
    Some("bracketleftex"),
    Some("bracketleftbt"),
    Some("bracelefttp"),
    Some("braceleftmid"),
    Some("braceleftbt"),
    Some("braceex"),
    None,
    Some("angleright"),
    Some("integral"),
    Some("integraltp"),
    Some("integralex"),
    Some("integralbt"),
    Some("parenrighttp"),
    Some("parenrightex"),
    Some("parenrightbt"),
    Some("bracketrighttp"),
    Some("bracketrightex"),
    Some("bracketrightbt"),
    Some("bracerighttp"),
    Some("bracerightmid"),
    Some("bracerightbt"),
    None,
];

static ZAPF_DINGBATS_ENCODING: [Option<&str>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("space"),
    Some("a1"),
    Some("a2"),
    Some("a202"),
    Some("a3"),
    Some("a4"),
    Some("a5"),
    Some("a119"),
    Some("a118"),
    Some("a117"),
    Some("a11"),
    Some("a12"),
    Some("a13"),
    Some("a14"),
    Some("a15"),
    Some("a16"),
    Some("a105"),
    Some("a17"),
    Some("a18"),
    Some("a19"),
    Some("a20"),
    Some("a21"),
    Some("a22"),
    Some("a23"),
    Some("a24"),
    Some("a25"),
    Some("a26"),
    Some("a27"),
    Some("a28"),
    Some("a6"),
    Some("a7"),
    Some("a8"),
    Some("a9"),
    Some("a10"),
    Some("a29"),
    Some("a30"),
    Some("a31"),
    Some("a32"),
    Some("a33"),
    Some("a34"),
    Some("a35"),
    Some("a36"),
    Some("a37"),
    Some("a38"),
    Some("a39"),
    Some("a40"),
    Some("a41"),
    Some("a42"),
    Some("a43"),
    Some("a44"),
    Some("a45"),
    Some("a46"),
    Some("a47"),
    Some("a48"),
    Some("a49"),
    Some("a50"),
    Some("a51"),
    Some("a52"),
    Some("a53"),
    Some("a54"),
    Some("a55"),
    Some("a56"),
    Some("a57"),
    Some("a58"),
    Some("a59"),
    Some("a60"),
    Some("a61"),
    Some("a62"),
    Some("a63"),
    Some("a64"),
    Some("a65"),
    Some("a66"),
    Some("a67"),
    Some("a68"),
    Some("a69"),
    Some("a70"),
    Some("a71"),
    Some("a72"),
    Some("a73"),
    Some("a74"),
    Some("a203"),
    Some("a75"),
    Some("a204"),
    Some("a76"),
    Some("a77"),
    Some("a78"),
    Some("a79"),
    Some("a81"),
    Some("a82"),
    Some("a83"),
    Some("a84"),
    Some("a97"),
    Some("a98"),
    Some("a99"),
    Some("a100"),
    None,
    Some("a89"),
    Some("a90"),
    Some("a93"),
    Some("a94"),
    Some("a91"),
    Some("a92"),
    Some("a205"),
    Some("a85"),
    Some("a206"),
    Some("a86"),
    Some("a87"),
    Some("a88"),
    Some("a95"),
    Some("a96"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some("a101"),
    Some("a102"),
    Some("a103"),
    Some("a104"),
    Some("a106"),
    Some("a107"),
    Some("a108"),
    Some("a112"),
    Some("a111"),
    Some("a110"),
    Some("a109"),
    Some("a120"),
    Some("a121"),
    Some("a122"),
    Some("a123"),
    Some("a124"),
    Some("a125"),
    Some("a126"),
    Some("a127"),
    Some("a128"),
    Some("a129"),
    Some("a130"),
    Some("a131"),
    Some("a132"),
    Some("a133"),
    Some("a134"),
    Some("a135"),
    Some("a136"),
    Some("a137"),
    Some("a138"),
    Some("a139"),
    Some("a140"),
    Some("a141"),
    Some("a142"),
    Some("a143"),
    Some("a144"),
    Some("a145"),
    Some("a146"),
    Some("a147"),
    Some("a148"),
    Some("a149"),
    Some("a150"),
    Some("a151"),
    Some("a152"),
    Some("a153"),
    Some("a154"),
    Some("a155"),
    Some("a156"),
    Some("a157"),
    Some("a158"),
    Some("a159"),
    Some("a160"),
    Some("a161"),
    Some("a163"),
    Some("a164"),
    Some("a196"),
    Some("a165"),
    Some("a192"),
    Some("a166"),
    Some("a167"),
    Some("a168"),
    Some("a169"),
    Some("a170"),
    Some("a171"),
    Some("a172"),
    Some("a173"),
    Some("a162"),
    Some("a174"),
    Some("a175"),
    Some("a176"),
    Some("a177"),
    Some("a178"),
    Some("a179"),
    Some("a193"),
    Some("a180"),
    Some("a199"),
    Some("a181"),
    Some("a200"),
    Some("a182"),
    None,
    Some("a201"),
    Some("a183"),
    Some("a184"),
    Some("a197"),
    Some("a185"),
    Some("a194"),
    Some("a198"),
    Some("a186"),
    Some("a195"),
    Some("a187"),
    Some("a188"),
    Some("a189"),
    Some("a190"),
    Some("a191"),
    None,
];

// ZapfDingbats glyph names (a1..a206) are not in the AGL; this table maps them
// to the Unicode Dingbats block so the fallback font glyph lookup can resolve
// them. Sorted by name for binary search.
static ZAPF_DINGBATS_TO_UNICODE: [(&str, char); 201] = [
    ("a1", '\u{2701}'),
    ("a10", '\u{2721}'),
    ("a100", '\u{275E}'),
    ("a101", '\u{2761}'),
    ("a102", '\u{2762}'),
    ("a103", '\u{2763}'),
    ("a104", '\u{2764}'),
    ("a105", '\u{2710}'),
    ("a106", '\u{2765}'),
    ("a107", '\u{2766}'),
    ("a108", '\u{2767}'),
    ("a109", '\u{2660}'),
    ("a11", '\u{261B}'),
    ("a110", '\u{2665}'),
    ("a111", '\u{2666}'),
    ("a112", '\u{2663}'),
    ("a117", '\u{2709}'),
    ("a118", '\u{2708}'),
    ("a119", '\u{2707}'),
    ("a12", '\u{261E}'),
    ("a120", '\u{2460}'),
    ("a121", '\u{2461}'),
    ("a122", '\u{2462}'),
    ("a123", '\u{2463}'),
    ("a124", '\u{2464}'),
    ("a125", '\u{2465}'),
    ("a126", '\u{2466}'),
    ("a127", '\u{2467}'),
    ("a128", '\u{2468}'),
    ("a129", '\u{2469}'),
    ("a13", '\u{270C}'),
    ("a130", '\u{2776}'),
    ("a131", '\u{2777}'),
    ("a132", '\u{2778}'),
    ("a133", '\u{2779}'),
    ("a134", '\u{277A}'),
    ("a135", '\u{277B}'),
    ("a136", '\u{277C}'),
    ("a137", '\u{277D}'),
    ("a138", '\u{277E}'),
    ("a139", '\u{277F}'),
    ("a14", '\u{270D}'),
    ("a140", '\u{2780}'),
    ("a141", '\u{2781}'),
    ("a142", '\u{2782}'),
    ("a143", '\u{2783}'),
    ("a144", '\u{2784}'),
    ("a145", '\u{2785}'),
    ("a146", '\u{2786}'),
    ("a147", '\u{2787}'),
    ("a148", '\u{2788}'),
    ("a149", '\u{2789}'),
    ("a15", '\u{270E}'),
    ("a150", '\u{278A}'),
    ("a151", '\u{278B}'),
    ("a152", '\u{278C}'),
    ("a153", '\u{278D}'),
    ("a154", '\u{278E}'),
    ("a155", '\u{278F}'),
    ("a156", '\u{2790}'),
    ("a157", '\u{2791}'),
    ("a158", '\u{2792}'),
    ("a159", '\u{2793}'),
    ("a16", '\u{270F}'),
    ("a160", '\u{2794}'),
    ("a161", '\u{2192}'),
    ("a162", '\u{27A3}'),
    ("a163", '\u{2194}'),
    ("a164", '\u{2195}'),
    ("a165", '\u{2799}'),
    ("a166", '\u{279B}'),
    ("a167", '\u{279C}'),
    ("a168", '\u{279D}'),
    ("a169", '\u{279E}'),
    ("a17", '\u{2711}'),
    ("a170", '\u{279F}'),
    ("a171", '\u{27A0}'),
    ("a172", '\u{27A1}'),
    ("a173", '\u{27A2}'),
    ("a174", '\u{27A4}'),
    ("a175", '\u{27A5}'),
    ("a176", '\u{27A6}'),
    ("a177", '\u{27A7}'),
    ("a178", '\u{27A8}'),
    ("a179", '\u{27A9}'),
    ("a18", '\u{2712}'),
    ("a180", '\u{27AB}'),
    ("a181", '\u{27AD}'),
    ("a182", '\u{27AF}'),
    ("a183", '\u{27B2}'),
    ("a184", '\u{27B3}'),
    ("a185", '\u{27B5}'),
    ("a186", '\u{27B8}'),
    ("a187", '\u{27BA}'),
    ("a188", '\u{27BB}'),
    ("a189", '\u{27BC}'),
    ("a19", '\u{2713}'),
    ("a190", '\u{27BD}'),
    ("a191", '\u{27BE}'),
    ("a192", '\u{279A}'),
    ("a193", '\u{27AA}'),
    ("a194", '\u{27B6}'),
    ("a195", '\u{27B9}'),
    ("a196", '\u{2798}'),
    ("a197", '\u{27B4}'),
    ("a198", '\u{27B7}'),
    ("a199", '\u{27AC}'),
    ("a2", '\u{2702}'),
    ("a20", '\u{2714}'),
    ("a200", '\u{27AE}'),
    ("a201", '\u{27B1}'),
    ("a202", '\u{2703}'),
    ("a203", '\u{2750}'),
    ("a204", '\u{2752}'),
    ("a205", '\u{276E}'),
    ("a206", '\u{2770}'),
    ("a21", '\u{2715}'),
    ("a22", '\u{2716}'),
    ("a23", '\u{2717}'),
    ("a24", '\u{2718}'),
    ("a25", '\u{2719}'),
    ("a26", '\u{271A}'),
    ("a27", '\u{271B}'),
    ("a28", '\u{271C}'),
    ("a29", '\u{2722}'),
    ("a3", '\u{2704}'),
    ("a30", '\u{2723}'),
    ("a31", '\u{2724}'),
    ("a32", '\u{2725}'),
    ("a33", '\u{2726}'),
    ("a34", '\u{2727}'),
    ("a35", '\u{2605}'),
    ("a36", '\u{2729}'),
    ("a37", '\u{272A}'),
    ("a38", '\u{272B}'),
    ("a39", '\u{272C}'),
    ("a4", '\u{260E}'),
    ("a40", '\u{272D}'),
    ("a41", '\u{272E}'),
    ("a42", '\u{272F}'),
    ("a43", '\u{2730}'),
    ("a44", '\u{2731}'),
    ("a45", '\u{2732}'),
    ("a46", '\u{2733}'),
    ("a47", '\u{2734}'),
    ("a48", '\u{2735}'),
    ("a49", '\u{2736}'),
    ("a5", '\u{2706}'),
    ("a50", '\u{2737}'),
    ("a51", '\u{2738}'),
    ("a52", '\u{2739}'),
    ("a53", '\u{273A}'),
    ("a54", '\u{273B}'),
    ("a55", '\u{273C}'),
    ("a56", '\u{273D}'),
    ("a57", '\u{273E}'),
    ("a58", '\u{273F}'),
    ("a59", '\u{2740}'),
    ("a6", '\u{271D}'),
    ("a60", '\u{2741}'),
    ("a61", '\u{2742}'),
    ("a62", '\u{2743}'),
    ("a63", '\u{2744}'),
    ("a64", '\u{2745}'),
    ("a65", '\u{2746}'),
    ("a66", '\u{2747}'),
    ("a67", '\u{2748}'),
    ("a68", '\u{2749}'),
    ("a69", '\u{274A}'),
    ("a7", '\u{271E}'),
    ("a70", '\u{274B}'),
    ("a71", '\u{25CF}'),
    ("a72", '\u{274D}'),
    ("a73", '\u{25A0}'),
    ("a74", '\u{274F}'),
    ("a75", '\u{2751}'),
    ("a76", '\u{25B2}'),
    ("a77", '\u{25BC}'),
    ("a78", '\u{25C6}'),
    ("a79", '\u{2756}'),
    ("a8", '\u{271F}'),
    ("a81", '\u{25D7}'),
    ("a82", '\u{2758}'),
    ("a83", '\u{2759}'),
    ("a84", '\u{275A}'),
    ("a85", '\u{276F}'),
    ("a86", '\u{2771}'),
    ("a87", '\u{2772}'),
    ("a88", '\u{2773}'),
    ("a89", '\u{2768}'),
    ("a9", '\u{2720}'),
    ("a90", '\u{2769}'),
    ("a91", '\u{276C}'),
    ("a92", '\u{276D}'),
    ("a93", '\u{276A}'),
    ("a94", '\u{276B}'),
    ("a95", '\u{2774}'),
    ("a96", '\u{2775}'),
    ("a97", '\u{275B}'),
    ("a98", '\u{275C}'),
    ("a99", '\u{275D}'),
];

/// Resolve a ZapfDingbats glyph name (e.g. "a1") to its Unicode codepoint.
pub fn zapf_dingbats_name_to_unicode(name: &str) -> Option<char> {
    ZAPF_DINGBATS_TO_UNICODE
        .binary_search_by(|(n, _)| n.cmp(&name))
        .ok()
        .map(|i| ZAPF_DINGBATS_TO_UNICODE[i].1)
}


pub struct Encoding;

impl Encoding {
    pub fn lookup(encoding_name: &str, byte: u8) -> &'static str {
        let table = match encoding_name {
            "StandardEncoding" | "Adobe-Standard" => &STANDARD_ENCODING,
            "WinAnsiEncoding" | "WinAnsi" => &WIN_ANSI_ENCODING,
            "MacRomanEncoding" | "MacRoman" => &MAC_ROMAN_ENCODING,
            "PDFDocEncoding" => &PDF_DOC_ENCODING,
            "SymbolEncoding" | "Symbol" => &SYMBOL_ENCODING,
            "ZapfDingbatsEncoding" | "ZapfDingbats" | "Dingbats" => &ZAPF_DINGBATS_ENCODING,
            _ => return ".notdef",
        };
        table[byte as usize].unwrap_or(".notdef")
    }

    pub fn apply_differences(base: &str, differences: &[Operand]) -> Vec<String> {
        let mut table: Vec<String> = (0u8..=255)
            .map(|byte| Self::lookup(base, byte).to_string())
            .collect();
        let mut current_code: usize = 0;
        for item in differences {
            match item {
                Operand::Integer(n) if *n >= 0 => {
                    current_code = *n as usize;
                }
                Operand::Name(name) => {
                    if current_code < 256 {
                        table[current_code] = name.clone();
                    }
                    current_code = current_code.saturating_add(1);
                }
                _ => {}
            }
        }
        table
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fonts::glyph_list::glyph_name_to_unicode;
    use crate::fonts::resolver::expand_ligature;

    #[test]
    fn standard_encoding_lookup() {
        assert_eq!(Encoding::lookup("StandardEncoding", 0x41), "A");
        assert_eq!(Encoding::lookup("StandardEncoding", 0x27), "quoteright");
        assert_eq!(Encoding::lookup("StandardEncoding", 0xAE), "fi");
        assert_eq!(Encoding::lookup("StandardEncoding", 0x00), ".notdef");
    }

    #[test]
    fn win_ansi_encoding_lookup() {
        assert_eq!(Encoding::lookup("WinAnsiEncoding", 0x80), "Euro");
        assert_eq!(Encoding::lookup("WinAnsiEncoding", 0x27), "quotesingle");
    }

    #[test]
    fn symbol_encoding_maps_greek_and_math() {
        // 0x61 'a' -> alpha, 0x53 'S' -> Sigma, 0xE5 -> summation, 0xF2 -> integral.
        assert_eq!(Encoding::lookup("Symbol", 0x61), "alpha");
        assert_eq!(Encoding::lookup("SymbolEncoding", 0x53), "Sigma");
        assert_eq!(Encoding::lookup("Symbol", 0xE5), "summation");
        assert_eq!(Encoding::lookup("Symbol", 0xF2), "integral");
        // And those glyph names resolve to the expected Unicode points.
        assert_eq!(glyph_name_to_unicode("alpha"), Some('\u{03B1}'));
        assert_eq!(glyph_name_to_unicode("Sigma"), Some('\u{03A3}'));
        assert_eq!(glyph_name_to_unicode("summation"), Some('\u{2211}'));
        assert_eq!(glyph_name_to_unicode("integral"), Some('\u{222B}'));
    }

    #[test]
    fn zapf_dingbats_encoding_maps_to_dingbat_glyph_names() {
        // 0x21 '!' -> a1 (scissors-class), 0x6C -> a71 (black circle).
        assert_eq!(Encoding::lookup("ZapfDingbats", 0x21), "a1");
        assert_eq!(Encoding::lookup("ZapfDingbatsEncoding", 0x6C), "a71");
        // The dingbat names resolve to the Unicode Dingbats block.
        assert_eq!(glyph_name_to_unicode("a1"), Some('\u{2701}'));
        assert_eq!(glyph_name_to_unicode("a71"), Some('\u{25CF}')); // black circle
        assert_eq!(zapf_dingbats_name_to_unicode("a19"), Some('\u{2713}')); // check mark
    }

    #[test]
    fn differences_override_base_encoding() {
        let diffs = vec![
            Operand::Integer(0x27),
            Operand::Name("testsymbol".to_string()),
            Operand::Integer(0x60),
            Operand::Name("testaccent".to_string()),
        ];
        let table = Encoding::apply_differences("StandardEncoding", &diffs);
        assert_eq!(table[0x27], "testsymbol");
        assert_eq!(table[0x60], "testaccent");
        assert_eq!(table[0x41], "A");
    }

    #[test]
    fn agl_lookup_handles_common_names_and_unicode_names() {
        assert_eq!(glyph_name_to_unicode("A"), Some('A'));
        assert_eq!(glyph_name_to_unicode("emdash"), Some('\u{2014}'));
        assert_eq!(glyph_name_to_unicode("fi"), Some('\u{FB01}'));
        assert_eq!(glyph_name_to_unicode("quoteright"), Some('\u{2019}'));
        assert_eq!(glyph_name_to_unicode("Euro"), Some('\u{20AC}'));
        assert_eq!(glyph_name_to_unicode("uniABCD"), Some('\u{ABCD}'));
        assert_eq!(glyph_name_to_unicode("notaname"), None);
    }

    #[test]
    fn expands_ligatures() {
        assert_eq!(expand_ligature('\u{FB01}'), "fi");
        assert_eq!(expand_ligature('\u{FB02}'), "fl");
        assert_eq!(expand_ligature('A'), "A");
    }
}
