//! Integration tests for digital signature verification (`pdfsig`-equivalent).
//!
//! Fixtures are generated by `scripts/make_signature_fixtures.py` (pyHanko + a
//! self-signed RSA/SHA-256 cert we control, so the ground truth is known):
//!   sig_valid.pdf - one valid signature covering the whole file
//!   sig_two.pdf   - signed twice (two signature fields)
//!
//! The tampered and modified-after-signing cases are derived from
//! sig_valid.pdf at test time (mutate / append bytes), so they don't need to be
//! committed.
//!
//! NOTE: Poppler's `pdfsig` is not bundled in this environment, so the
//! cross-check is against the KNOWN GROUND TRUTH (we control the cert/key and
//! pyHanko independently confirms intact=valid), not against `pdfsig`. The
//! objective findings (cryptographic validity + coverage + signer details) are
//! exactly what a `pdfsig` cross-check would compare.

use std::path::PathBuf;

use oxide_engine::{ContentEngine, Coverage, PdfSigner, SignatureOptions, SignatureValidity};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn fixture_bytes(name: &str) -> Vec<u8> {
    std::fs::read(fixture(name)).expect("fixture present (run make_signature_fixtures.py)")
}

fn fixture_pem(name: &str) -> String {
    let raw = std::fs::read_to_string(fixture(name)).expect("PEM fixture present");
    let mut pem = raw
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n");
    pem.push('\n');
    pem
}

fn test_signer() -> PdfSigner {
    PdfSigner::from_pem(
        &fixture_pem("sign_test_rsa_key.pem"),
        &fixture_pem("sign_test_rsa_cert.pem"),
        &[],
    )
    .expect("test signer parses")
}

#[test]
fn rsa_signing_appends_valid_incremental_signature() {
    let original = fixture_bytes("minimal.pdf");
    let e = ContentEngine::open_bytes(original.clone()).unwrap();
    let options = SignatureOptions {
        field_name: "OxideSig1".to_string(),
        signer_name: Some("Oxide SDK Signing Test".to_string()),
        reason: Some("integration test".to_string()),
        location: Some("test suite".to_string()),
        signing_time: Some("D:20260622000000Z".to_string()),
        rect: Some([36.0, 36.0, 260.0, 96.0]),
        ..SignatureOptions::default()
    };

    let signed = e.sign(&test_signer(), &options).unwrap();
    assert!(
        signed.starts_with(&original),
        "incremental signing must preserve the original bytes as a prefix"
    );
    assert!(signed.len() > original.len());

    let signed_engine = ContentEngine::open_bytes(signed.clone()).unwrap();
    let reports = signed_engine.verify_signatures().unwrap();
    assert_eq!(reports.len(), 1);
    let r = &reports[0];
    assert_eq!(r.field_name.as_deref(), Some("OxideSig1"));
    assert_eq!(r.signer_name.as_deref(), Some("Oxide SDK Signing Test"));
    assert_eq!(r.reason.as_deref(), Some("integration test"));
    assert_eq!(r.location.as_deref(), Some("test suite"));
    assert_eq!(r.validity, SignatureValidity::Valid);
    assert_eq!(r.coverage, Coverage::WholeFile);
    assert_eq!(r.digest_algorithm.as_deref(), Some("SHA-256"));
    let cert = r.certificate.as_ref().expect("signer cert reported");
    assert!(cert.subject.contains("Oxide SDK Signing Test"));
    assert_eq!(cert.serial_hex, "20260801");

    let mut tampered = signed;
    let pos = tampered
        .windows(2)
        .position(|w| w == b"Hi")
        .expect("page content marker present");
    tampered[pos] = b'X';
    let tampered_engine = ContentEngine::open_bytes(tampered).unwrap();
    let tampered_report = &tampered_engine.verify_signatures().unwrap()[0];
    assert_eq!(tampered_report.validity, SignatureValidity::Invalid);
}

#[test]
fn valid_signature_is_cryptographically_valid_with_cert_details() {
    let e = ContentEngine::open_bytes(fixture_bytes("sig_valid.pdf")).unwrap();
    let reports = e.verify_signatures().unwrap();
    assert_eq!(reports.len(), 1, "expected exactly one signature");
    let r = &reports[0];

    assert_eq!(r.validity, SignatureValidity::Valid);
    assert_eq!(r.coverage, Coverage::WholeFile);
    assert_eq!(r.digest_algorithm.as_deref(), Some("SHA-256"));

    let cert = r.certificate.as_ref().expect("signer cert reported");
    assert!(
        cert.subject.contains("Oxide Test Signer"),
        "subject was {}",
        cert.subject
    );
    assert_eq!(cert.serial_hex, "1234ABCD");
    // Honest-scope note must be present.
    assert!(
        r.note.contains("NOT checked"),
        "scope note missing: {}",
        r.note
    );
}

#[test]
fn tampering_within_signed_range_invalidates() {
    let mut bytes = fixture_bytes("sig_valid.pdf");
    // Flip a byte inside the page content (within the first signed range).
    let pos = bytes
        .windows(2)
        .position(|w| w == b"Hi")
        .expect("page content marker present");
    bytes[pos] = b'X';

    let e = ContentEngine::open_bytes(bytes).unwrap();
    let r = &e.verify_signatures().unwrap()[0];
    assert_eq!(
        r.validity,
        SignatureValidity::Invalid,
        "a byte changed inside the signed range must invalidate the signature"
    );
}

#[test]
fn appending_after_signing_is_valid_but_modified() {
    let mut bytes = fixture_bytes("sig_valid.pdf");
    // Append bytes after the signed ranges (an incremental-update tail).
    bytes.extend_from_slice(b"\n% appended after signing\n1 0 obj<<>>endobj\n");

    let e = ContentEngine::open_bytes(bytes).unwrap();
    let r = &e.verify_signatures().unwrap()[0];
    // The signature is still cryptographically valid for what it covered...
    assert_eq!(r.validity, SignatureValidity::Valid);
    // ...but the document was modified after signing.
    assert_eq!(r.coverage, Coverage::ModifiedAfterSigning);
}

#[test]
fn multiple_signatures_are_all_reported() {
    let e = ContentEngine::open_bytes(fixture_bytes("sig_two.pdf")).unwrap();
    let reports = e.verify_signatures().unwrap();
    assert_eq!(reports.len(), 2, "both signature fields must be reported");

    // Both signatures verify cryptographically.
    for r in &reports {
        assert_eq!(
            r.validity,
            SignatureValidity::Valid,
            "signature {} should be valid",
            r.index
        );
        assert!(r.certificate.is_some());
    }

    // The FIRST signature no longer covers the whole file (the second
    // signature's incremental update is appended after it); the SECOND covers
    // the whole file. This is the standard pdfsig "modified after signing"
    // distinction for the earlier of two signatures.
    assert_eq!(reports[0].coverage, Coverage::ModifiedAfterSigning);
    assert_eq!(reports[1].coverage, Coverage::WholeFile);
}

#[test]
fn unsigned_document_reports_no_signatures() {
    // A normal PDF with no signature fields lists empty (not an error).
    let e = ContentEngine::open_bytes(fixture_bytes("minimal.pdf")).unwrap();
    let reports = e.verify_signatures().unwrap();
    assert!(
        reports.is_empty(),
        "unsigned document must report no signatures"
    );
}

#[test]
fn signer_name_or_metadata_present() {
    // pyHanko records the signer; at minimum a field name is present.
    let e = ContentEngine::open_bytes(fixture_bytes("sig_valid.pdf")).unwrap();
    let r = &e.verify_signatures().unwrap()[0];
    assert!(
        r.field_name.is_some(),
        "the signature field name should be reported"
    );
    assert_eq!(r.field_name.as_deref(), Some("Sig1"));
}
